### ISSUE TITLE
Example code not running properly?

### ISSUE THREAD

**Issue by Johnson-Stephen** [biocore/calour#77]
Hello,

I've followed the installation instructions to set up a conda environment for calour, but I can't seem to get any of the plotting functionality to work. When I try and run the example plotting code, I get the following:

```
>>> import calour as ca
>>> a = ca.read_amplicon('test2.biom', 'test2.sample', feature_metadata_file='test2.feature', min_reads=100, normalize=1000)
>>> b = a.plot(sample_field='group',
...            bary_fields=['oxygen'], 
...            barx_fields=['group', 'categorical'],
...            barx_label_kwargs=[{'color': 'b'}, {'color': 'white', 'size': 9}],
...            cmap='inferno',
...            gui='cli',
...            title='simple figure');
Traceback (most recent call last):
  File "/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/site-packages/calour/database.py", line 39, in _get_database_class
    db_module = importlib.import_module(module_name)
  File "/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/site-packages/dbbact_calour/dbbact.py", line 21, in <module>
    fileConfig(log, disable_existing_loggers=False)
  File "/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/logging/config.py", line 76, in fileConfig
    formatters = _create_formatters(cp)
  File "/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/logging/config.py", line 109, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/configparser.py", line 956, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/site-packages/calour/util.py", line 129, in inner
    return func(*args, **kwargs)
  File "/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/site-packages/calour/heatmap/heatmap.py", line 510, in plot
    gui_obj = _create_plot_gui(exp, gui, databases)
  File "/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/site-packages/calour/heatmap/heatmap.py", line 63, in _create_plot_gui
    cdb = _get_database_class(cdatabase, exp=exp)
  File "/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/site-packages/calour/database.py", line 41, in _get_database_class
    raise ValueError('Database interface %s not installed. Did you do pip install for it?' % module_name)
ValueError: Database interface dbbact_calour.dbbact not installed. Did you do pip install for it?
```

I've tried installing dbbact_calour, although the documentation says it is optional, but I still get the same error.

**Comment by amnona** [comment]
Hi,
thanks for the report :)
As a temp. workaround, you can run the plot without the dbbact database
interface by adding: databases=[] to the plot command parameters.

But we should make it work with the database.
1. Did you install dbbact_calour while inside the calour conda environment?
2. Can you try to run (within the calour notebook you are working on):
import dbbact_calour
to see if dbbact_calour is installed and is available in your python path?

let me know how it works
Amnon

**Comment by Johnson-Stephen** [comment]
Thanks, adding `databases=[] ` allowed me to run the code without any error
However dbbact_calour still doesn't work -- if I run the exact same code in the original post but include an `import dbbact_calour` statement at the start, I get the same output (no errors from the import statement)

**Comment by amnona** [comment]
strange.
can you try the following (after activating the calour environment using
"source activate calour"):

import calour as ca
import importlib
db_module = importlib.import_module('dbbact_calour.dbbact')

and send me the output? (this is the way calour imports the database
modules...)

Also, just to be on the safe side, send also the output of the following
commands:

ca.util.get_config_file()
ca.util.get_config_sections()
ca.util.get_config_value('class_name', section='dbbact')
ca.util.get_config_value('module_name', section='dbbact')

Thanks
Amnon

**Comment by Johnson-Stephen** [comment]
Here's the output from the first block:
```
>>> import calour as ca
>>> import importlib
>>> db_module = importlib.import_module('dbbact_calour.dbbact')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/site-packages/dbbact_calour/dbbact.py", line 21, in <module>
    fileConfig(log, disable_existing_loggers=False)
  File "/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/logging/config.py", line 76, in fileConfig
    formatters = _create_formatters(cp)
  File "/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/logging/config.py", line 109, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/configparser.py", line 956, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'
```

And here's the output from the second block:
```
>>> ca.util.get_config_file()
'/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/site-packages/calour/calour.config'
>>> ca.util.get_config_sections()
['dbbact', 'sponge', 'gnps']
>>> ca.util.get_config_value('class_name', section='dbbact')
'DBBact'
>>> ca.util.get_config_value('module_name', section='dbbact')
'dbbact_calour.dbbact'
```

**Comment by amnona** [comment]
Thanks
seems like there is a problem loading the logger config file used for
dbbact_calour.
I modified the dbbact_calour code. can you try (after source activate
calour):
pip uninstall dbbact_calour
pip install git+git://github.com/amnona/dbbact-calour

And let me know if it works now? (or if it fails, attach again the output
of: db_module = importlib.import_module('dbbact_calour.dbbact')

thanks :)

**Comment by Johnson-Stephen** [comment]
It looks like I get the same error with the modified dbbact_calour:

```
>>> import calour as ca
>>> import importlib
>>> db_module = importlib.import_module('dbbact_calour.dbbact')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/site-packages/dbbact_calour/dbbact.py", line 22, in <module>
    fileConfig(log, disable_existing_loggers=False)
  File "/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/logging/config.py", line 76, in fileConfig
    formatters = _create_formatters(cp)
  File "/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/logging/config.py", line 109, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/configparser.py", line 956, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'
```

**Comment by amnona** [comment]
arrrrgh
ok, i added a temp. workaround (try/except) and in the except a debug
message.

Can you try again:
source activate calour
pip uninstall dbbact_calour
pip install git+git://github.com/amnona/dbbact-calour

and see if it works and also send me the debug message it prints (something
like "FAILED loading logging config file XXXXX")

thanks
amnon

**Comment by amnona** [comment]
ok, think i found the bug - the log.cgf file was not in the setup.py
package resource list.
Should work now.
just reinstall dbbact-calour:
source activate calour
pip uninstall dbbact_calour
pip install git+git://github.com/amnona/dbbact-calour

Let me know if you still get the "FAILED loading logging config file..."
error message (or if there are any problems/errors)

thanks
amnon

**Comment by Johnson-Stephen** [comment]
Still getting the error:
```
>>> import calour as ca
>>> import importlib
>>> db_module = importlib.import_module('dbbact_calour.dbbact')
FAILED loading logging config file /data2/bsi/staff_analysis/m141127/miniconda3/envs/calour/lib/python3.5/site-packages/dbbact_calour/log.cfg
```

But it looks like that log file doesn't exist? If I do a `ls` on that directory, I just see the following:
```
dbannotation.py  dbbact.py  __init__.py  __pycache__/  requests
```

**Comment by amnona** [comment]
thanks.
managed recreate locally. you are correct - it seems the file is not copied
during the install.
will try to fix locally and send :)

**Comment by amnona** [comment]
ok. should be working now (at least stopped causing the bug on my computer).
Problem was the package name in the setup.py package_data was dbbact-calour
and not dbbact_calour
Thanks for all the reporting, patience and help.

Let me know if it (finally) works :)

Amnon

**Comment by Johnson-Stephen** [comment]
It works! Thank you so much!
